# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
