# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180414_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='y',
            new_name='lng',
        ),
    ]
