# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180414_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='title',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
