# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_point_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='visited',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
