# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_point_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
